In [2]:
# Numpy Array

In [3]:
my_list=[1,2,3]

In [5]:
import numpy as np

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(5,5)

array([[0.32026447, 0.17889447, 0.04938409, 0.65316908, 0.88321671],
       [0.33189247, 0.63340396, 0.92188251, 0.6918971 , 0.8193695 ],
       [0.65077195, 0.86677876, 0.02848993, 0.14359955, 0.21587786],
       [0.15561517, 0.60711902, 0.5758844 , 0.55423566, 0.22830521],
       [0.73779545, 0.09179054, 0.3693017 , 0.21751883, 0.72133531]])

In [28]:
np.random.randn(4,4)

array([[-0.39792657, -0.52162337, -0.13724974,  1.35119456],
       [ 0.55184302,  0.14617666,  1.62305609, -0.69896831],
       [-0.75574538, -0.4428486 ,  0.61452964,  1.32120083],
       [ 0.4858509 , -1.51665531, -1.28903321, -2.74564131]])

In [30]:
np.random.randint(1,100,10)

array([ 8, 24, 75, 61, 70, 65, 19,  5, 29, 52])

In [31]:
arr=np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr=np.random.randint(0,50,10)

In [34]:
ranarr

array([21, 20,  2, 29, 26, 12, 25, 22,  7, 33])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr

array([21, 20,  2, 29, 26, 12, 25, 22,  7, 33])

In [40]:
ranarr.max()

33

In [41]:
ranarr.min()

2

In [42]:
ranarr.argmax()

9

In [43]:
arr.shape

(25,)

In [44]:
arr=arr.reshape(5,5)

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.shape

(5, 5)

In [47]:
arr.dtype

dtype('int32')

In [49]:
from numpy.random import randint

In [50]:
randint(2,10)

2